name: Test setup-maven action

on:
  workflow_call:
    secrets: inherit

env:
  CURL_ASSERT_SCRIPT: >-
    $(curl
    --silent
    --show-error
    --fail-with-body
    --retry 5
    --retry-all-errors
    https://raw.githubusercontent.com/hazelcast/assert.sh/main/assert.sh)


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v7
        with:
          repository: hazelcast/hazelcast
          path: hazelcast

      - name: Run setup-maven
        id: setup-maven
        uses: $/setup-maven

      - name: Test outputs
        run: |
          source /dev/stdin <<< "${CURL_ASSERT_SCRIPT}"

          TESTS_RESULT=0

          assert_non_empty() {
            local actual=$1
            local name=$2
            local msg="${name} should not be empty"
            assert_not_empty "${actual}" "$msg" && log_success "${msg}" || TESTS_RESULT=$?
          }

          assert_non_empty "${{ steps.setup-maven.outputs.local-repository }}" "local-repository"
          assert_non_empty "${{ steps.setup-maven.outputs.cache-key }}" "cache-key"
          assert_non_empty "${{ steps.setup-maven.outputs.cache-hit }}" "cache-hit"

          assert_eq 0 "$TESTS_RESULT" "All tests should pass"

      - name: Run setup-maven with GPG
        id: setup-maven-gpg
        uses: $/setup-maven
        with:
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}

      - name: Verify GPG signing via Maven
        run: |
          source /dev/stdin <<< "${CURL_ASSERT_SCRIPT}"
          TESTS_RESULT=0

          mvn gpg:sign-and-deploy-file \
            -f hazelcast/pom.xml \
            -DpomFile=pom.xml \
            -Durl=file:\${project.basedir} \
            --batch-mode || true

          assert_true "[ -f hazelcast/pom.xml.asc ]" "The project directory should contain the pom.xml.asc signature file" || TESTS_RESULT=$?

          assert_eq 0 "$TESTS_RESULT" "All GPG verification tests should pass"
        env:
          GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
