name: Test setup-maven action

on:
  workflow_call:

env:
  CURL_ASSERT_SCRIPT: curl --fail --retry 5 --retry-all-errors --show-error --silent https://raw.githubusercontent.com/hazelcast/assert.sh/main/assert.sh

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v7
        with:
          repository: hazelcast/hazelcast
          path: hazelcast

      - name: Run setup-maven
        id: setup-maven
        uses: $/setup-maven
        with:
          root: hazelcast
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}

      - name: Test outputs
        run: |
          source /dev/stdin <<< "$(${CURL_ASSERT_SCRIPT})"

          TESTS_RESULT=0

          assert_non_empty() {
            local actual=$1
            local name=$2
            local msg="${name} should not be empty"
            assert_not_empty "${actual}" "$msg" && log_success "${msg}" || TESTS_RESULT=$?
          }

          assert_non_empty "${{ steps.setup-maven.outputs.local-repository }}" "local-repository"
          assert_non_empty "${{ steps.setup-maven.outputs.cache-key }}" "cache-key"
          assert_non_empty "${{ steps.setup-maven.outputs.cache-hit }}" "cache-hit"

          assert_eq 0 "${TESTS_RESULT}" "All tests should pass"

      - name: Test GPG signing
        run: |
          set +e
          source /dev/stdin <<< "$(${CURL_ASSERT_SCRIPT})"
          TESTS_RESULT=0

          (
          cd hazelcast && \
            ./mvnw gpg:sign-and-deploy-file \
              -DpomFile=pom.xml \
              -Dfile=pom.xml \
              -Durl=file://.
          ) || true

          [ -f "$(find hazelcast -name "hazelcast-root-*.pom.ascXX" | head -n 1)" ]; file_exists=$?
          msg="The signed pom.asc should be generated"
          assert_eq 0 "${file_exists}" "${msg}" && log_success "${msg}" || TESTS_RESULT=$?

          assert_eq 0 "${TESTS_RESULT}" "All tests should pass"
        env:
          GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}


